### ISSUE TITLE
Please Add me to the Community

### ISSUE THREAD

**Issue by Hardly-Human** [1upCommunity/.github#3]

**Comment by N3RDIUM** [comment]
Sure!

**Comment by N3RDIUM** [comment]
I've invited you to the organization.

**Comment by N3RDIUM** [comment]
Also, to contact us, please use the Contact-us repository.

**Comment by N3RDIUM** [comment]
Your avatar will appear on the [website](https://1upCommunity.github.io) next week.

**Comment by N3RDIUM** [comment]
Done
