### ISSUE TITLE
Please add me to the community

### ISSUE THREAD

**Issue by cixtor** [1upCommunity/.github#5]
I have been an active member of the open-source community on GitHub and other platforms, and it is always a joy to find young developers forming communities to share knowledge and experiences. I would love to join thir GitHub organization to help many more developers become excellent open-source maintainers.

**Comment by N3RDIUM** [comment]
@cixtor I've sent you an invite.

**Comment by N3RDIUM** [comment]
@cixtor Also, view the organisation's profile as a member and look at the readme. The 1up discord invite link is provided on the page. If you have a discord account, please join the server.
